steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-hook', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-hook']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
    - 'run'
    - 'deploy'
    - 'news-hook'
    - '--image'
    - 'gcr.io/$PROJECT_ID/news-hook'
    - '--region'
    - 'southamerica-east1'
    - '--platform'
    - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/news-hook'