steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-hook', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-hook']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google-cloud-sdk/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'news-hook'
    - '--image'
    - 'gcr.io/$PROJECT_ID/news-hook'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/news-hook'
