steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-hook', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-hook']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
    - 'run'
    - 'deploy'
    - 'news-hook'
    - '--image'
    - 'gcr.io/$PROJECT_ID/news-hook'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances'
    - '$$CLOUD_SQL_CONNECTION_NAME'
    - '--service-account'
    - '$$SERVICE_ACCOUNT'

images:
  - 'gcr.io/$PROJECT_ID/news-hook'

# Substitutions for sensitive values
substitutions:
  _CLOUD_SQL_CONNECTION_NAME: ''  # Fill this with the output of: gcloud sql instances describe news-hook-db --format="value(connectionName)"
  _SERVICE_ACCOUNT: ''  # Fill this with the service account email from: gcloud iam service-accounts list