steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-hook', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-hook']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
    - 'run'
    - 'deploy'
    - 'news-hook'
    - '--image'
    - 'gcr.io/$PROJECT_ID/news-hook'
    - '--region'
    - 'southamerica-east1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances'
    - '$$CLOUD_SQL_CONNECTION_NAME'
    - '--service-account'
    - '$$SERVICE_ACCOUNT'
    - '--port'
    - '8080'
    - '--command'
    - 'uvicorn'
    - '--args'
    - 'app.main:app,--host,0.0.0.0,--port,8080'

images:
  - 'gcr.io/$PROJECT_ID/news-hook'