"""drop_payload_format

Revision ID: 01b6e9c61e71
Revises: 70018e041536
Create Date: 2025-07-03 00:54:49.425570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01b6e9c61e71'
down_revision: Union[str, None] = '70018e041536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_alert_chats_created_at'), table_name='alert_chats')
    op.drop_index(op.f('idx_alert_chats_prompt_embedding_cosine'), table_name='alert_chats', postgresql_using='ivfflat')
    op.create_index('idx_created_at', 'alert_chats', ['created_at'], unique=False)
    op.create_index('idx_prompt_embedding_cosine', 'alert_chats', ['prompt_embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'prompt_embedding': 'vector_cosine_ops'})
    op.drop_column('alert_prompts', 'payload_format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_prompts', sa.Column('payload_format', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('idx_prompt_embedding_cosine', table_name='alert_chats', postgresql_using='ivfflat', postgresql_ops={'prompt_embedding': 'vector_cosine_ops'})
    op.drop_index('idx_created_at', table_name='alert_chats')
    op.create_index(op.f('idx_alert_chats_prompt_embedding_cosine'), 'alert_chats', ['prompt_embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index(op.f('idx_alert_chats_created_at'), 'alert_chats', ['created_at'], unique=False)
    # ### end Alembic commands ###
