"""llm_validation_reason

Revision ID: 278b44774fbd
Revises: 4badfa99a94f
Create Date: 2025-05-14 02:41:06.817282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278b44774fbd'
down_revision: Union[str, None] = '4badfa99a94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_validations', sa.Column('reason', sa.String(length=128), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_validations', 'reason')
    # ### end Alembic commands ###
