"""add_agent_controller_and_remove_user_documents

Revision ID: 37e634688625
Revises: 911c66a91178
Create Date: 2025-05-21 17:06:40.132767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '37e634688625'
down_revision: Union[str, None] = '911c66a91178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_documents')
    op.add_column('monitored_data', sa.Column('agent_controller_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'monitored_data', 'agent_controllers', ['agent_controller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monitored_data', type_='foreignkey')
    op.drop_column('monitored_data', 'agent_controller_id')
    op.create_table('user_documents',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('agent_controller_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('uploaded_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_embedding', Vector(dim=768), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_controller_id'], ['agent_controllers.id'], name='user_documents_agent_controller_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_documents_pkey')
    )
    # ### end Alembic commands ###
