"""llm_validation_alert_prompt_relationship

Revision ID: 4badfa99a94f
Revises: dc20b13f50cf
Create Date: 2025-05-14 02:27:07.601388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4badfa99a94f'
down_revision: Union[str, None] = 'dc20b13f50cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_validations', sa.Column('prompt', sa.String(length=255), nullable=False))
    op.alter_column('llm_validations', 'prompt_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_validations', 'prompt_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('llm_validations', 'prompt')
    # ### end Alembic commands ###
