"""alert_chat_user_fields

Revision ID: 70018e041536
Revises: 846232299b6b
Create Date: 2025-07-02 22:48:39.864423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70018e041536'
down_revision: Union[str, None] = '846232299b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_chats', sa.Column('username', sa.String(), nullable=True))
    op.add_column('alert_chats', sa.Column('language_code', sa.String(), nullable=True))
    op.add_column('alert_chats', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('alert_chats', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompt_embedding_cosine', table_name='alert_chats', postgresql_using='ivfflat', postgresql_ops={'prompt_embedding': 'vector_cosine_ops'})
    op.drop_index('idx_created_at', table_name='alert_chats')
    op.create_index(op.f('idx_alert_chats_prompt_embedding_cosine'), 'alert_chats', ['prompt_embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index(op.f('idx_alert_chats_created_at'), 'alert_chats', ['created_at'], unique=False)
    op.drop_column('alert_chats', 'last_name')
    op.drop_column('alert_chats', 'first_name')
    op.drop_column('alert_chats', 'language_code')
    op.drop_column('alert_chats', 'username')
    # ### end Alembic commands ###
