"""add_alert_chat_id_to_alert_event

Revision ID: 846232299b6b
Revises: 9a5b174c7974
Create Date: 2025-07-02 12:41:17.253300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '846232299b6b'
down_revision: Union[str, None] = '9a5b174c7974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('prompt_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIGGERED', 'CANCELLED', 'WARNED', 'EXPIRED', name='alertchatstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_chats_created_at', 'alert_chats', ['created_at'], unique=False)
    op.create_index('idx_alert_chats_prompt_embedding_cosine', 'alert_chats', ['prompt_embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'prompt_embedding': 'vector_cosine_ops'})
    op.add_column('alert_events', sa.Column('alert_chat_id', sa.String(length=36), nullable=True))
    op.alter_column('alert_events', 'alert_prompt_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'alert_events', 'alert_chats', ['alert_chat_id'], ['id'])
    op.add_column('llm_validations', sa.Column('alert_chat_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'llm_validations', 'alert_chats', ['alert_chat_id'], ['id'])
    op.add_column('llm_verifications', sa.Column('alert_chat_id', sa.String(length=36), nullable=True))
    op.alter_column('llm_verifications', 'alert_prompt_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'llm_verifications', 'alert_chats', ['alert_chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_verifications', type_='foreignkey')
    op.alter_column('llm_verifications', 'alert_prompt_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('llm_verifications', 'alert_chat_id')
    op.drop_constraint(None, 'llm_validations', type_='foreignkey')
    op.drop_column('llm_validations', 'alert_chat_id')
    op.drop_constraint(None, 'alert_events', type_='foreignkey')
    op.alter_column('alert_events', 'alert_prompt_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('alert_events', 'alert_chat_id')
    op.drop_index('idx_alert_chats_prompt_embedding_cosine', table_name='alert_chats', postgresql_using='ivfflat', postgresql_ops={'prompt_embedding': 'vector_cosine_ops'})
    op.drop_index('idx_alert_chats_created_at', table_name='alert_chats')
    op.drop_table('alert_chats')
    # ### end Alembic commands ###
