"""savings

Revision ID: 9a5b174c7974
Revises: 10eb656ecfc3
Create Date: 2025-06-25 23:17:27.280485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5b174c7974'
down_revision: Union[str, None] = '10eb656ecfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add status_code as nullable first
    op.add_column('alert_events', sa.Column('status_code', sa.Integer(), nullable=True))
    
    # Update existing rows with a default value (200 for success)
    op.execute("UPDATE alert_events SET status_code = 200 WHERE status_code IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('alert_events', 'status_code', nullable=False)
    
    # Add the document_id column and foreign key
    op.add_column('llm_verifications', sa.Column('document_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'llm_verifications', 'monitored_data', ['document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_verifications', type_='foreignkey')
    op.drop_column('llm_verifications', 'document_id')
    op.drop_column('alert_events', 'status_code')
    # ### end Alembic commands ###