"""fixing_alert_sending

Revision ID: 9dfc110ccf47
Revises: 34ada6ad7026
Create Date: 2025-05-16 20:12:18.658627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dfc110ccf47'
down_revision: Union[str, None] = '34ada6ad7026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('exception', sa.String(), nullable=True))
    op.add_column('alert_events', sa.Column('structured_data', sa.JSON(), nullable=True))
    op.drop_column('alert_events', 'response')
    op.add_column('monitored_data', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('monitored_data', sa.Column('monitored_datetime', sa.DateTime(), nullable=False))
    op.drop_index('idx_scraped_datetime', table_name='monitored_data')
    op.create_index('idx_monitored_datetime', 'monitored_data', ['monitored_datetime'], unique=False)
    op.drop_column('monitored_data', 'scraped_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_data', sa.Column('scraped_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index('idx_monitored_datetime', table_name='monitored_data')
    op.create_index('idx_scraped_datetime', 'monitored_data', ['scraped_datetime'], unique=False)
    op.drop_column('monitored_data', 'monitored_datetime')
    op.drop_column('monitored_data', 'name')
    op.add_column('alert_events', sa.Column('response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('alert_events', 'structured_data')
    op.drop_column('alert_events', 'exception')
    # ### end Alembic commands ###
